apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - port: 3000        # Internal cluster port
      targetPort: 3000  # App's container port
      nodePort: 32000   # Port to access from localhost
