name: Build, Test, Scan, and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build - Compile code
        run: npm run build

      - name: Test - Run unit tests
        run: npm test

      - name: Lint/Code Quality - Lint code
        run: npm run lint

      - name: Security Scan - npm audit
        run: npm audit --audit-level=high

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${REPO_LC}/nextjs-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${REPO_LC}/nextjs-app:${{ github.sha }}
